### ISSUE TITLE
Hafiz!!

### ISSUE THREAD

**Issue by imranismail** [hafizio/symphony_api#1]
Nice.. ko pon learning Elixir, bila la nak buat facebook. Susah betul nak contact

**Comment by hafizio** [comment]
@imranismail dude, aku baru request untuk join elixirmy group. Buat last week mini hackathon dengan member. Checkout his repo as well https://github.com/jianyaoang/Symphony-iOS. Phoenix is quite similar to Rails. Not as matured yet. But definitely a strong rival. It's fun to learn elixir. https://www.facebook.com/mhafizkhairudin but i'm not active, usually only use for facebook integration. haha
